### ISSUE TITLE
Spelling variations

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/fhir-zulip-nlp-analysis#17]
## Summary
Need to utilize new `spelling_variations` column in the [Google Sheet](https://docs.google.com/spreadsheets/d/1OB0CEAkOhVTN71uIhzCo_iNaiD1B6qLqL7uwil5O22Q/edit#gid=1136391153).

## Additional info
At some point, we should probably refactor to use the [NLP library that Stephanie recommended](https://github.com/jhu-bids/fhir-zulip-nlp-analysis/issues/1#issuecomment-1158232808).

I don't think it's important to break down the results by which spelling variations were used. Can just aggregate all the results for all variations by and label it by what's in the `keyword` column.

**Comment by stephanieshong** [comment]
one word or two words are supported

**Comment by joeflack4** [comment]
I'm working on this now but my current understanding is that we will / should not use `nltk` for the spelling variations part of things. The reason is that we basically have 2 options starting out when it comes to getting raw text from zulip:
a. Get _all_ the data from Zulip, then parse it.
b. Use Zulip's endpoints and query features to query certain keywords, on certain streams, etc.

We've went with (b). I think this is actually the better option simply because Zulip has a rate limit for how much we can query.
